# Generated by Django 4.1.3 on 2023-10-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_of_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
